export enum Genre {
  Fantasy = 'Fantasy',
  Action = 'Action',
  Romance = 'Romance',
  Horror = 'Horror',
  Drama = 'Drama',
  War = 'War',
  Animation = 'Animation',
  Thriller = 'Thriller',
  SciFi = 'Sci-Fi',
  History = 'History',
  Mystery = 'Mystery',
  Family = 'Family',
  Adventure = 'Adventure',
  Crime = 'Crime',
  Comedy = 'Comedy',
  FilmNoir = 'Film-Noir',
  Biography = 'Biography',
}
