name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint all projects
        run: npx nx run-many --target=lint --all

      - name: Test all projects
        run: npx nx run-many --target=test --all --ci --coverage --passWithNoTests
