name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint all libs
        run: |
          npx nx lint review
          npx nx lint movie
          npx nx lint watchlistitem

      - name: Test review lib
        run: |
          npx nx test review --ci --coverage

      - name: Test movie lib
        run: |
          npx nx test movie --ci --coverage

      - name: Test watchlistitem lib
        run: |
          npx nx test watchlistitem --ci --coverage
