name: Build and deploy data-backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and prepare data-backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build data-backend
        run: npx nx build data-backend

      - name: Install runtime dependencies in dist
        run: |
          cd dist/apps/data-backend
          npm install --omit=dev

      - name: Zip data-backend for deployment
        run: |
          cd dist/apps/data-backend
          zip -r ../../data-backend-release.zip .

      - name: Upload artifact for deploy step
        uses: actions/upload-artifact@v4
        with:
          name: data-backend
          path: dist/data-backend-release.zip

  deploy-data-api:
    runs-on: ubuntu-latest
    name: Deploy NestJs data-backend
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: data-backend

      - name: Unzip artifact
        run: unzip data-backend-release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'data-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NESTJS_PUBLISHPROFILE }}
          package: .
