name: Build and deploy frontend and backend app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and zip apps from /dist
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Prepare rcmnd-backend dependencies
        run: |
          # Copy root package files to rcmnd-backend dist
          cp package.json package-lock.json dist/apps/rcmnd-backend/

      - name: Zip artifacts for deployment
        run: |
          echo "Zipping artifacts from ${GITHUB_WORKSPACE}/dist/apps/"
          cd ${GITHUB_WORKSPACE}/dist/apps/data-backend/ && zip ${GITHUB_WORKSPACE}/data-backend-release.zip ./* -r
          cd ${GITHUB_WORKSPACE}/dist/apps/rcmnd-backend/ && zip ${GITHUB_WORKSPACE}/rcmnd-backend-release.zip ./* -r
          cd ${GITHUB_WORKSPACE}/dist/apps/nx-react-nestjs/ && zip ${GITHUB_WORKSPACE}/nx-react-nestjs-release.zip ./* -r

      # Rest of the upload steps remain the same...

      - name: Upload nx-react-nestjs artifact
        uses: actions/upload-artifact@v4
        with:
          name: nx-react-nestjs
          path: nx-react-nestjs-release.zip

      - name: Upload data-backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-backend
          path: data-backend-release.zip

      - name: Upload rcmnd-backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: rcmnd-backend
          path: rcmnd-backend-release.zip

  deploy-nx-react-nestjs:
    # Keep original working configuration unchanged
    runs-on: ubuntu-latest
    name: Deploy Angular Frontend
    needs: build
    environment:
      name: 'Production'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nx-react-nestjs
      - run: unzip nx-react-nestjs-release.zip
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.REACT_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          output_location: 'dist/apps/nx-react-nestjs'

  deploy-data-backend:
    # Keep original working configuration unchanged
    runs-on: ubuntu-latest
    name: Deploy data-backend
    needs: build
    environment:
      name: 'Production'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: data-backend
      - run: unzip data-backend-release.zip
      - run: npm install
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'data-backend'
          publish-profile: ${{ secrets.NESTJS_PUBLISHPROFILE }}
          package: .

  deploy-rcmnd-backend:
    runs-on: ubuntu-latest
    name: Deploy rcmnd-backend
    needs: build
    environment:
      name: 'Production'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: rcmnd-backend
      - run: unzip rcmnd-backend-release.zip

      - name: Install dependencies
        run: npm install --production

      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'rcmnd-backend'
          publish-profile: ${{ secrets.RCMND_PUBLISHTOKEN }}
          package: .
