# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy frontend and backend app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

# ... rest of your workflow

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and zip apps from /dist
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Copy package files for backends
        run: |
          # Copy package.json and package-lock.json for each backend into their dist directories
          cp apps/data-backend/package.json dist/apps/data-backend/
          cp apps/data-backend/package-lock.json dist/apps/data-backend/
          cp apps/rcmnd-backend/package.json dist/apps/rcmnd-backend/
          cp apps/rcmnd-backend/package-lock.json dist/apps/rcmnd-backend/

      - name: Zip artifacts for deployment
        run: |
          cd ${GITHUB_WORKSPACE}/dist/apps/data-backend/ && zip ${GITHUB_WORKSPACE}/data-backend-release.zip ./* -r
          cd ${GITHUB_WORKSPACE}/dist/apps/rcmnd-backend/ && zip ${GITHUB_WORKSPACE}/rcmnd-backend-release.zip ./* -r
          cd ${GITHUB_WORKSPACE}/dist/apps/nx-react-nestjs/ && zip ${GITHUB_WORKSPACE}/nx-react-nestjs-release.zip ./* -r

      # ... rest of the build job steps

  deploy-data-backend:
    runs-on: ubuntu-latest
    name: Deploy NestJs data-backend backend
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: data-backend

      - name: Unzip artifact for deployment
        run: unzip data-backend-release.zip

      - name: Install dependencies
        run: npm install --production

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'data-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NESTJS_PUBLISHPROFILE }}
          package: .

  deploy-rcmnd-backend:
    runs-on: ubuntu-latest
    name: Deploy NestJs rcmnd-backend backend
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: rcmnd-backend

      - name: Unzip artifact for deployment
        run: unzip rcmnd-backend-release.zip

      - name: Install dependencies
        run: npm install --production

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rcmnd-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.RCMND_PUBLISHTOKEN }}
          package: .
